### ISSUE TITLE
Command Injection inside the ls command

### ISSUE THREAD

**Issue by guillaumemichel** [AAA97AAA/SoftSec#2]
The `ls` command is not properly sanitized before the call to `popen`, and the command `mkdir` allows to create a directory containing the character ';', and `cd` allows changing directory to a directory containing the character ';'. Thus, it is possible to create a directory, let's say `;xcalc`, to `cd` to it, and then use `ls` to execute the `xcalc` command.
Location: ls.cpp, line 34 (ls command), ls.cpp, line 24 (popen)

Here is the input to give to the client to open a calculator (with a user KevinMitnick and password FreeKevin)
```
>>> login KevinMitnick
>>> pass FreeKevin
>>> mkdir ;xcalc
>>> cd ;xcalc
>>> ls
```

**Comment by hazimeh** [comment]
Fixed in commit c656d1cbf74eaa886b9be99fda312d8a5803e500
